const fs = require('fs');
const path = require('path');
const i18nDir = 'src/lib/i18n';
const langs = ['ar.json', 'en.json', 'id.json', 'ja.json', 'ko.json', 'zh.json'];

const data = {
  'id.json': {
    'title': 'Ikhtisar MAZEEDA',
    'guruku_title': 'Guruku',
    'pengajar': 'Pengajar',
    'guruku_desc': 'Mustahiq | Mustahiqoh | Munawwib | Munawibah',
    'squad_title': 'Mazeeda Squad',
    'anggota': 'Anggota',
    'squad_desc': 'Alumni | Alumnus',
    'timeline_title': 'Time Line',
    'momen': 'Momen',
    'timeline_desc': 'Foto kenangan | album memori',
    'sangu_title': 'Sangu | Wirid',
    'berkas': 'Berkas',
    'sangu_desc': 'Koleksi doa | sholawat | nadzom',
    'quran_title': "Al-Qur'an Progress",
    'quran_ayat': 'Ayat - Terakhir Dibaca',
    'quran_surah': 'Surah Pertama',
    'ai_title': 'MAZEEDA AI',
    'ai_tanya': 'Tanya AI',
    'ai_desc': 'Teman curhat & asisten cerdas',
    'akademik_title': 'Riwayat Akademik',
    'akademik_nilai': 'Daftar Nilai',
    'akademik_desc': 'Cari | lihat daftar nilai siswi',
    'jejak_title': 'Jejak MAZEEDA',
    'jejak_perjalanan': 'Perjalanan Kami',
    'jejak_desc': '2023 - 2032 · Eksplorasi Kenangan'
  },
  'en.json': {
    'title': 'MAZEEDA Overview',
    'guruku_title': 'My Teachers',
    'pengajar': 'Teachers',
    'guruku_desc': 'Mustahiq | Mustahiqoh | Munawwib | Munawibah',
    'squad_title': 'Mazeeda Squad',
    'anggota': 'Members',
    'squad_desc': 'Alumni | Alumnus',
    'timeline_title': 'Time Line',
    'momen': 'Moments',
    'timeline_desc': 'Memories photos | memory album',
    'sangu_title': 'Sangu | Wirid',
    'berkas': 'Files',
    'sangu_desc': 'Collection of prayers | sholawat | nadzom',
    'quran_title': "Al-Qur'an Progress",
    'quran_ayat': 'Verses - Last Read',
    'quran_surah': 'First Surah',
    'ai_title': 'MAZEEDA AI',
    'ai_tanya': 'Ask AI',
    'ai_desc': 'Confidant & smart assistant',
    'akademik_title': 'Academic History',
    'akademik_nilai': 'Transcripts',
    'akademik_desc': 'Search | view student transcripts',
    'jejak_title': 'MAZEEDA Traces',
    'jejak_perjalanan': 'Our Journey',
    'jejak_desc': '2023 - 2032 · Exploring Memories'
  },
  'ar.json': {
    'title': 'لمحة عن مزيدة',
    'guruku_title': 'معلمي',
    'pengajar': 'معلماً',
    'guruku_desc': 'مستحق | مستحقة | مناوب | مناوبة',
    'squad_title': 'فريق مزيدة',
    'anggota': 'عضواً',
    'squad_desc': 'خريجون | خريجات',
    'timeline_title': 'الجدول الزمني',
    'momen': 'لحظات',
    'timeline_desc': 'صور الذكريات | ألبوم الذكريات',
    'sangu_title': 'الأوراد والزاد',
    'berkas': 'ملفاً',
    'sangu_desc': 'مجموعة الأدعية | الصلوات | النظم',
    'quran_title': 'تقدم القرآن',
    'quran_ayat': 'آيات - آخر ما قُرىء',
    'quran_surah': 'السورة الأولى',
    'ai_title': 'مزيدة للذكاء الاصطناعي',
    'ai_tanya': 'اسأل الذكاء الاصطناعي',
    'ai_desc': 'صديق مقرب ومساعد ذكي',
    'akademik_title': 'السجل الأكاديمي',
    'akademik_nilai': 'كشف الدرجات',
    'akademik_desc': 'ابحث | شاهد درجات الطالبات',
    'jejak_title': 'آثار مزيدة',
    'jejak_perjalanan': 'رحلتنا',
    'jejak_desc': '2023 - 2032 · استكشاف الذكريات'
  },
  'ja.json': {
    'title': 'マゼーダ概要',
    'guruku_title': '私の先生',
    'pengajar': '人の先生',
    'guruku_desc': 'ムスタヒク | ムスタヒコ | ムナウィブ | ムナウィバ',
    'squad_title': 'マゼーダスクワッド',
    'anggota': '人のメンバー',
    'squad_desc': '卒業生 | 同窓生',
    'timeline_title': 'タイムライン',
    'momen': 'の瞬間',
    'timeline_desc': '思い出の写真 | メモリアルバム',
    'sangu_title': 'サング | ウィリド',
    'berkas': 'ファイル',
    'sangu_desc': '祈りのコレクション | ショラワット | ナゾム',
    'quran_title': 'コーランの進捗',
    'quran_ayat': '節 - 最後に読んだ',
    'quran_surah': '最初のスーラ',
    'ai_title': 'マゼーダAI',
    'ai_tanya': 'AIに聞く',
    'ai_desc': '親友＆スマートアシスタント',
    'akademik_title': '学業履歴',
    'akademik_nilai': '成績証明書',
    'akademik_desc': '検索 | 学生の成績を見る',
    'jejak_title': 'マゼーダの足跡',
    'jejak_perjalanan': '私たちの旅',
    'jejak_desc': '2023 - 2032 · 思い出を探求する'
  },
  'zh.json': {
    'title': 'MAZEEDA 概述',
    'guruku_title': '我的老师',
    'pengajar': '名教师',
    'guruku_desc': 'Mustahiq | Mustahiqoh | Munawwib | Munawibah',
    'squad_title': 'Mazeeda 小队',
    'anggota': '名成员',
    'squad_desc': '校友 | 毕业生',
    'timeline_title': '时间线',
    'momen': '个瞬间',
    'timeline_desc': '回忆照片 | 纪念相册',
    'sangu_title': 'Sangu | Wirid',
    'berkas': '个文件',
    'sangu_desc': '祈祷文合集 | sholawat | nadzom',
    'quran_title': '古兰经进度',
    'quran_ayat': '节 - 最后阅读',
    'quran_surah': '第一章',
    'ai_title': 'MAZEEDA AI',
    'ai_tanya': '询问 AI',
    'ai_desc': '知己与智能助手',
    'akademik_title': '学术历史',
    'akademik_nilai': '成绩单',
    'akademik_desc': '搜索 | 查看学生成绩',
    'jejak_title': 'MAZEEDA 足迹',
    'jejak_perjalanan': '我们的旅程',
    'jejak_desc': '2023 - 2032 · 探索回忆'
  },
  'ko.json': {
    'title': 'MAZEEDA 개요',
    'guruku_title': '나의 선생님',
    'pengajar': '명의 선생님',
    'guruku_desc': '무스타히크 | 무스타히코 | 무나위브 | 무나위바',
    'squad_title': '마제다 스쿼드',
    'anggota': '명의 회원',
    'squad_desc': '동문 | 졸업생',
    'timeline_title': '타임라인',
    'momen': '개의 순간',
    'timeline_desc': '추억 사진 | 기념 앨범',
    'sangu_title': '상구 | 위리드',
    'berkas': '개의 파일',
    'sangu_desc': '기도 모음 | 숄라왓 | 나좀',
    'quran_title': '코란 진행 상황',
    'quran_ayat': '절 - 마지막으로 읽음',
    'quran_surah': '첫 번째 수라',
    'ai_title': '마제다 AI',
    'ai_tanya': 'AI에게 물어보기',
    'ai_desc': '절친 & 스마트 어시스턴트',
    'akademik_title': '학업 기록',
    'akademik_nilai': '성적 증명서',
    'akademik_desc': '검색 | 학생 성적 보기',
    'jejak_title': '마제다 발자취',
    'jejak_perjalanan': '우리의 여정',
    'jejak_desc': '2023 - 2032 · 추억 탐험'
  }
};

for (const lang of langs) {
  const fp = path.join(i18nDir, lang);
  let content = JSON.parse(fs.readFileSync(fp, 'utf8'));
  content.ikhtisar = data[lang];
  fs.writeFileSync(fp, JSON.stringify(content, null, 2));
}
console.log("Done updating ikhtisar i18n");
