const fs = require('fs');
const path = require('path');
const i18nDir = 'src/lib/i18n';
const langs = ['ar.json', 'en.json', 'id.json', 'ja.json', 'ko.json', 'zh.json'];

const data = {
  'id.json': {
    'title': 'Fitur Islami',
    'qibla_badge': '🧭 Kompas Arah',
    'qibla_title': 'Arah Kiblat',
    'qibla_desc': 'Cari arah kiblat sholat secara real-time dengan HP atau GPS.',
    'zakat_badge': '🧮 Hitung Zakat',
    'zakat_title': 'Kalkulator Zakat',
    'zakat_desc': 'Hitung Zakat Penghasilan, Maal, Emas, Peternakan, Saham, dll.',
    'faraidh_badge': '⚖️ Pembagian Waris',
    'faraidh_title': 'Kalkulator Faraidh',
    'faraidh_desc': 'Hitung pembagian waris secara syariat Islam dengan mudah.',
    'calendar_badge': '📅 Kalender',
    'calendar_title': 'Masehi & Hijriah',
    'calendar_desc': 'Lihat penanggalan Masehi dan Hijriah secara interaktif dalam satu layar.',
    'tasbih_badge': '📿 Zikir Pintar',
    'tasbih_title': 'Tasbih Digital',
    'tasbih_desc': 'Hitung dan simpan zikir harianmu secara otomatis.',
    'cashflow_badge': '💳 Manajemen Uang',
    'cashflow_title': 'Cash Flow',
    'cashflow_desc': 'Catat Cash Flow harianmu dengan mudah dan aman sebagaimana isyarat QS. Al-Baqarah: 282.',
    'kas_badge': '🤝 Donasi / Kas',
    'kas_title': 'Kas Angkatan',
    'kas_desc': 'Dukung kemaslahatan bersama melalui kontribusi Kas Angkatan.'
  },
  'en.json': {
    'title': 'Islamic Features',
    'qibla_badge': '🧭 Qibla Compass',
    'qibla_title': 'Qibla Direction',
    'qibla_desc': 'Find the Qibla direction in real-time using your phone or GPS.',
    'zakat_badge': '🧮 Calculate Zakat',
    'zakat_title': 'Zakat Calculator',
    'zakat_desc': 'Calculate Zakat on Income, Wealth, Gold, Livestock, Stocks, etc.',
    'faraidh_badge': '⚖️ Inheritance Division',
    'faraidh_title': 'Faraidh Calculator',
    'faraidh_desc': 'Easily calculate inheritance division according to Islamic law.',
    'calendar_badge': '📅 Calendar',
    'calendar_title': 'Gregorian & Hijri',
    'calendar_desc': 'View Gregorian and Hijri dates interactively on one screen.',
    'tasbih_badge': '📿 Smart Dhikr',
    'tasbih_title': 'Digital Tasbih',
    'tasbih_desc': 'Count and save your daily dhikr automatically.',
    'cashflow_badge': '💳 Money Management',
    'cashflow_title': 'Cash Flow',
    'cashflow_desc': 'Record your daily cash flow easily and safely as suggested in Surah Al-Baqarah: 282.',
    'kas_badge': '🤝 Donation / Fund',
    'kas_title': 'Batch Fund',
    'kas_desc': 'Support mutual welfare through Batch Fund contributions.'
  },
  'ar.json': {
    'title': 'الميزات الإسلامية',
    'qibla_badge': '🧭 بوصلة القبلة',
    'qibla_title': 'اتجاه القبلة',
    'qibla_desc': 'ابحث عن اتجاه القبلة في الوقت الفعلي باستخدام الهاتف أو نظام تحديد المواقع العالمي (GPS).',
    'zakat_badge': '🧮 حساب الزكاة',
    'zakat_title': 'حاسبة الزكاة',
    'zakat_desc': 'احسب زكاة الدخل، المال، الذهب، الماشية، الأسهم، إلخ.',
    'faraidh_badge': '⚖️ تقسيم الميراث',
    'faraidh_title': 'حاسبة الفرائض',
    'faraidh_desc': 'احسب تقسيم الميراث وفقاً للشريعة الإسلامية بسهولة.',
    'calendar_badge': '📅 التقويم',
    'calendar_title': 'الميلادي والهجري',
    'calendar_desc': 'اعرض التواريخ الميلادية والهجرية بشكل تفاعلي على شاشة واحدة.',
    'tasbih_badge': '📿 الذكر الذكي',
    'tasbih_title': 'المسبحة الرقمية',
    'tasbih_desc': 'احسب واحفظ أذكارك اليومية تلقائياً.',
    'cashflow_badge': '💳 إدارة الأموال',
    'cashflow_title': 'التدفق النقدي',
    'cashflow_desc': 'سجل تدفقاتك النقدية اليومية بسهولة وأمان كما أُشير في سورة البقرة: 282.',
    'kas_badge': '🤝 التبرع / الصندوق',
    'kas_title': 'صندوق الدفعة',
    'kas_desc': 'ادعم الرفاهية المشتركة من خلال مساهمات صندوق الدفعة.'
  },
  'ja.json': {
    'title': 'イスラム機能',
    'qibla_badge': '🧭 キブラコンパス',
    'qibla_title': 'キブラの方角',
    'qibla_desc': '携帯電話やGPSを使用して、リアルタイムでキブラの方向を見つけます。',
    'zakat_badge': '🧮 ザカート計算',
    'zakat_title': 'ザカート計算機',
    'zakat_desc': '収入、財産、金、家畜、株式などのザカートを計算します。',
    'faraidh_badge': '⚖️ 遺産分割',
    'faraidh_title': 'ファライド計算機',
    'faraidh_desc': 'イスラム法に基づく遺産分割を簡単に計算します。',
    'calendar_badge': '📅 カレンダー',
    'calendar_title': 'グレゴリオ暦とヒジュラ暦',
    'calendar_desc': 'グレゴリオ暦とヒジュラ暦の日付を1つの画面でインタラクティブに表示します。',
    'tasbih_badge': '📿 スマートズィクル',
    'tasbih_title': 'デジタルタスビーフ',
    'tasbih_desc': '毎日のズィクルを自動的にカウントして保存します。',
    'cashflow_badge': '💳 資金管理',
    'cashflow_title': 'キャッシュフロー',
    'cashflow_desc': 'クルアーン雌牛章282節で示唆されているように、毎日のキャッシュフローを簡単かつ安全に記録します。',
    'kas_badge': '🤝 寄付 / 基金',
    'kas_title': 'バッチ基金',
    'kas_desc': 'バッチ基金の貢献を通じて相互の福祉を支援します。'
  },
  'zh.json': {
    'title': '伊斯兰功能',
    'qibla_badge': '🧭 朝拜指南针',
    'qibla_title': '朝拜方向',
    'qibla_desc': '使用手机或GPS实时查找朝拜方向。',
    'zakat_badge': '🧮 天课计算',
    'zakat_title': '天课计算器',
    'zakat_desc': '计算收入、财富、黄金、牲畜、股票等的天课。',
    'faraidh_badge': '⚖️ 遗产分配',
    'faraidh_title': '法拉伊德计算器',
    'faraidh_desc': '轻松计算符合伊斯兰教法的遗产分配。',
    'calendar_badge': '📅 日历',
    'calendar_title': '公历与回历',
    'calendar_desc': '在一个屏幕上交互式查看公历和回历日期。',
    'tasbih_badge': '📿 智能念珠',
    'tasbih_title': '数字念珠',
    'tasbih_desc': '自动计数并保存您的每日念珠记录。',
    'cashflow_badge': '💳 资金管理',
    'cashflow_title': '现金流',
    'cashflow_desc': '如《黄牛章》第282节所暗示，轻松安全地记录您的每日现金流。',
    'kas_badge': '🤝 捐赠 / 基金',
    'kas_title': '班级基金',
    'kas_desc': '通过班级基金的贡献支持共同福利。'
  },
  'ko.json': {
    'title': '이슬람 기능',
    'qibla_badge': '🧭 키블라 나침반',
    'qibla_title': '키블라 방향',
    'qibla_desc': '휴대폰이나 GPS를 사용하여 실시간으로 키블라 방향을 찾으세요.',
    'zakat_badge': '🧮 자카트 계산',
    'zakat_title': '자카트 계산기',
    'zakat_desc': '소득, 재산, 금, 가축, 주식 등에 대한 자카트를 계산하세요.',
    'faraidh_badge': '⚖️ 상속 분할',
    'faraidh_title': '파라이드 계산기',
    'faraidh_desc': '이슬람 법에 따른 상속 분할을 쉽게 계산하세요.',
    'calendar_badge': '📅 달력',
    'calendar_title': '그레고리력 및 히즈라력',
    'calendar_desc': '그레고리력과 히즈라력 날짜를 한 화면에서 대화형으로 확인하세요.',
    'tasbih_badge': '📿 스마트 디크르',
    'tasbih_title': '디지털 타스비흐',
    'tasbih_desc': '매일의 디크르를 자동으로 세고 저장하세요.',
    'cashflow_badge': '💳 자금 관리',
    'cashflow_title': '현금 흐름',
    'cashflow_desc': '수라 알바카라 282절에 암시된 대로 매일의 현금 흐름을 쉽고 안전하게 기록하세요.',
    'kas_badge': '🤝 기부 / 기금',
    'kas_title': '배치 기금',
    'kas_desc': '배치 기금 기여를 통해 공동의 복지를 지원하세요.'
  }
};

for (const lang of langs) {
  const fp = path.join(i18nDir, lang);
  let content = JSON.parse(fs.readFileSync(fp, 'utf8'));
  content.islamic_features = data[lang];
  fs.writeFileSync(fp, JSON.stringify(content, null, 2));
}

console.log("Done updating i18n");
