import os
from PIL import Image
from rembg import remove, new_session

# Input files (Generated by AI)
inputs = {
    "journey_compass_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\mosque_new_1785701640820.jpg",
    "kepengurusan_bg_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\kepengurusan_new_1785701651894.jpg",
}

output_dir = r"C:\MAZEEDA\MAZEEDA CODING\New folder\static\images"

session = new_session("isnet-general-use")

for filename, input_path in inputs.items():
    output_path = os.path.join(output_dir, filename)
    print(f"Processing {filename}...")
    try:
        out_img = remove(Image.open(input_path), session=session)
        out_img.save(output_path, "PNG")
        print(f"Saved {filename}")
    except Exception as e:
        print(f"Failed {filename}: {e}")

print("Done! Replaced last 2 dark mode images.")
