import os
from PIL import Image
from rembg import remove, new_session

# Input files (Generated by AI)
zakat_input = r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\zakat_new_1785700280127.jpg"
faraidh_input = r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\faraidh_new_1785700289015.jpg"

# Output files in the project
zakat_output = r"C:\MAZEEDA\MAZEEDA CODING\New folder\static\images\zakat_bg_dark.png"
faraidh_output = r"C:\MAZEEDA\MAZEEDA CODING\New folder\static\images\faraidh_bg_dark.png"

session = new_session("isnet-general-use")

print("Processing new Zakat image...")
out_z = remove(Image.open(zakat_input), session=session)
out_z.save(zakat_output, "PNG")

print("Processing new Faraidh image...")
out_f = remove(Image.open(faraidh_input), session=session)
out_f.save(faraidh_output, "PNG")

print("Done! Replaced dark mode images with new generations.")
