import os
from PIL import Image
from rembg import remove, new_session

# Input files (Generated by AI)
inputs = {
    "kiblat_bg_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\kiblat_new_1785700653050.jpg",
    "kalender_bg_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\kalender_new_1785700662790.jpg",
    "tasbih_icon_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\tasbih_new_1785700671822.jpg",
    "cashflow_icon_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\cashflow_new_1785700682387.jpg",
    "kas_angkatan_icon_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\kas_new_1785700690321.jpg",
    "quiz_icon_dark.png": r"C:\Users\LENOVO\.gemini\antigravity\brain\38ff9938-4fd9-4743-87dc-25f2b15ae5c6\quiz_new_1785700699402.jpg",
}

output_dir = r"C:\MAZEEDA\MAZEEDA CODING\New folder\static\images"

session = new_session("isnet-general-use")

for filename, input_path in inputs.items():
    output_path = os.path.join(output_dir, filename)
    print(f"Processing {filename}...")
    try:
        out_img = remove(Image.open(input_path), session=session)
        out_img.save(output_path, "PNG")
        print(f"Saved {filename}")
    except Exception as e:
        print(f"Failed {filename}: {e}")

print("Done! Replaced all dark mode images with new generations.")
